/* V391 Project monthly metrics panel - reads monthly times directly */
(function(){
  'use strict';
  if(window.__tasneefProjectsMonthlyMetricsV391) return;
  window.__tasneefProjectsMonthlyMetricsV391 = true;
  const S=v=>String(v??'').trim(); const N=v=>{const n=Number(v||0);return Number.isFinite(n)?n:0};
  const $=id=>document.getElementById(id);
  const esc=v=>S(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sbc=()=>window.sb||window.supabaseClient||window._supabase||null;
  const pct=p=>N(p).toFixed(0)+'%'; const arMins=m=>{m=Math.round(N(m));const h=Math.floor(m/60),mm=m%60;if(!h)return mm+' دقيقة';if(!mm)return h+' ساعة';return h+' ساعة و '+mm+' دقيقة'};
  const norm=v=>S(v).replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[\u064B-\u0652]/g,'').replace(/\s+/g,' ').toLowerCase();
  const full=t=>{const n=norm(t);return n.includes('دوام')||n.includes('كامل')||n.includes('دائم')||n.includes('full')||n.includes('24')};
  const todayMonth=()=>new Date().toISOString().slice(0,7);
  async function safe(q){try{const r=await q;if(r.error)return[];return r.data||[]}catch(_){return[]}}
  function rowsFromSnap(s){if(!s)return[];if(Array.isArray(s))return s;if(Array.isArray(s.rows))return s.rows;return[]}
  function calc(rows){const map=new Map();(rows||[]).forEach(r=>{const name=S(r.projectName||r.project_name||r.name||r.project||'-');if(!name||name==='-')return;const k=S(r.projectId||r.project_id)||norm(name);const old=map.get(k)||{projectName:name,projectType:S(r.projectType||r.project_type||r.operation_type||'زيارة يومية'),supervisorName:S(r.supervisorName||r.supervisor_name||'-'),totalMinutes:0,requiredMinutes:0,percentage:0};old.totalMinutes=Math.max(N(old.totalMinutes),N(r.totalMinutes||r.total_minutes||r.minutes||0));old.requiredMinutes=Math.max(N(old.requiredMinutes),N(r.requiredMinutes||r.required_minutes||0));if(!old.supervisorName||old.supervisorName==='-')old.supervisorName=S(r.supervisorName||r.supervisor_name||'-');if(full(r.projectType||r.project_type))old.projectType='دوام كامل';map.set(k,old)});let out=[...map.values()];const daily=out.filter(x=>!full(x.projectType));const supTotals={};daily.forEach(r=>{const k=norm(r.supervisorName||'غير محدد');supTotals[k]=(supTotals[k]||0)+N(r.totalMinutes)});out.forEach(r=>{if(full(r.projectType))r.percentage=N(r.requiredMinutes)>0?N(r.totalMinutes)/N(r.requiredMinutes)*100:(N(r.totalMinutes)>0?100:0);else r.percentage=(supTotals[norm(r.supervisorName||'غير محدد')]||0)>0?N(r.totalMinutes)/(supTotals[norm(r.supervisorName||'غير محدد')]||0)*100:0});return out.sort((a,b)=>S(a.projectName).localeCompare(S(b.projectName),'ar'))}
  async function load(month){if(window.tasneefMonthlyV391Rows&&Array.isArray(window.tasneefMonthlyV391Rows))return calc(window.tasneefMonthlyV391Rows);const sb=sbc();let rows=[];if(sb){const snaps=await safe(sb.from('monthly_project_snapshots_v384').select('*').eq('month_key',month).order('updated_at',{ascending:false}).limit(20));snaps.forEach(s=>rows=rows.concat(rowsFromSnap(s)));}if(!rows.length){try{rows=rowsFromSnap(JSON.parse(localStorage.getItem('tasneef_monthly_snapshot_v384_'+month)||'{}'))}catch(_){}}return calc(rows)}
  function ensure(){const sec=$('projects');if(!sec)return false;if($('pm391Root'))return true;const style=document.createElement('style');style.textContent='.pm391{background:#fff;border:1px solid #dcebe6;border-radius:18px;padding:14px;margin:12px 0}.pm391-head{display:flex;justify-content:space-between;gap:10px;align-items:end;flex-wrap:wrap}.pm391-head h3{margin:0;color:#073f34}.pm391-head input{padding:10px;border:1px solid #cfe0da;border-radius:12px}.pm391-head button{border:0;border-radius:12px;background:#074f40;color:#fff;font-weight:900;padding:11px 14px}.pm391-table{width:100%;border-collapse:collapse;margin-top:12px}.pm391-table th,.pm391-table td{border:1px solid #dcebe6;padding:8px;text-align:center}.pm391-table th{background:#eef6f3;color:#073f34}.pm391-table td.project{text-align:right;font-weight:900;color:#073f34}.pm391-bar{height:10px;background:#e7f0ec;border-radius:999px;overflow:hidden}.pm391-bar span{height:100%;background:#074f40;display:block}';document.head.appendChild(style);const root=document.createElement('div');root.id='pm391Root';root.className='pm391';root.innerHTML='<div class="pm391-head"><div><h3>نسبة المشروع والوقت المستغرق من الأوقات الشهرية</h3><small>يقرأ الشهر المختار بدون تكرار المشاريع.</small></div><div><label>الشهر</label><input type="month" id="pm391Month"></div><button id="pm391Btn">عرض النسب</button></div><div style="overflow:auto"><table class="pm391-table"><thead><tr><th>المشروع</th><th>النوع</th><th>المشرف</th><th>الوقت المستغرق</th><th>الدقائق</th><th>نسبة المشروع</th></tr></thead><tbody id="pm391Body"><tr><td colspan="6">اختر الشهر ثم عرض النسب.</td></tr></tbody></table></div>';sec.prepend(root);$('pm391Month').value=todayMonth();$('pm391Btn').onclick=render;return true}
  async function render(){ensure();const m=$('pm391Month')?.value||todayMonth();const rows=await load(m);const body=$('pm391Body');if(body)body.innerHTML=rows.map(r=>`<tr><td class="project">${esc(r.projectName)}</td><td>${esc(r.projectType)}</td><td>${esc(r.supervisorName||'-')}</td><td>${esc(arMins(r.totalMinutes))}</td><td>${Math.round(N(r.totalMinutes)).toLocaleString('en-US')}</td><td><div class="pm391-bar"><span style="width:${Math.min(100,N(r.percentage)).toFixed(0)}%"></span></div><b>${pct(r.percentage)}</b></td></tr>`).join('')||'<tr><td colspan="6">لا توجد بيانات أوقات شهرية لهذا الشهر.</td></tr>'}
  window.addEventListener('tasneef:monthly-v391',e=>setTimeout(()=>{if($('projects')&&!$('projects').classList.contains('hidden'))render()},100));
  const oldShow=window.showPage;window.showPage=function(id,btn){const res=oldShow?oldShow.apply(this,arguments):undefined;if(id==='projects')setTimeout(()=>{ensure();render()},500);return res};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();
