/* Tasneef v10152 - Professional worker project time system
   تحضير العمال من السكن + توزيعهم على المشاريع + نقل عامل + مجموعات مشتركة + تقرير شهري
*/
(function(){
  'use strict';
  const VERSION='v10152-worker-project-time';
  const SUPABASE_URL='https://zmjdqiswytxlbfgnfjfv.supabase.co';
  const SUPABASE_ANON_KEY='sb_publishable_ADsAC5MtBCusDgX62c8NaQ_LyyuTPeb';
  const ATT='daily_worker_attendance', MOV='worker_project_movements', GRP='project_work_groups';
  const S=v=>String(v==null?'':v).trim(); const N=v=>Number(v||0)||0; const A=v=>Array.isArray(v)?v:[]; const $=id=>document.getElementById(id);
  const esc=s=>S(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  function today(){const d=new Date(),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
  function ymNow(){return today().slice(0,7)}
  function nowIso(){return new Date().toISOString()}
  function minutesBetween(a,b){const x=new Date(a),y=new Date(b);return Math.max(0,Math.round((y-x)/60000))}
  function readJson(x,d){try{return JSON.parse(x||'')||d}catch(_){return d}}
  function sb(){ if(window.sb&&window.sb.from)return window.sb; if(window.supabaseClient&&window.supabaseClient.from)return window.supabaseClient; if(window.supabase&&window.supabase.from)return window.supabase; if(window.supabase&&window.supabase.createClient){window.sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);return window.sb} return null; }
  function currentUser(){
    try{if(typeof window.session==='function')return window.session()||{}}catch(_){ }
    for(const st of [localStorage,sessionStorage]){for(const k of ['tasneef_user','tasneef_session','currentUser','user','loggedUser','tasneef_current_user','tasneef_login_user']){const o=readJson(st.getItem(k),null); if(o){const u=o.user||o.profile||o; if(u&&(u.id||u.name||u.full_name||u.username||u.email))return u;}}}
    return window.currentUser||window.loggedUser||{};
  }
  function userKey(){const u=currentUser();return S(u.id||u.user_id||u.username||u.email||u.full_name||u.name||'supervisor')}
  function userName(){const u=currentUser();return S(u.full_name||u.name||u.username||u.email||u.id||'المشرف')}
  function toast(t,type){
    let b=$('wptToast'); if(!b){b=document.createElement('div');b.id='wptToast';document.body.appendChild(b)}
    b.className='wpt-toast '+(type||''); b.textContent=t; requestAnimationFrame(()=>b.classList.add('show')); clearTimeout(window.__wptToast); window.__wptToast=setTimeout(()=>b.classList.remove('show'),2600);
  }
  function style(){ if($('wptStyle'))return; const st=document.createElement('style'); st.id='wptStyle'; st.textContent=`
    .wpt-card{background:#fff;border:1px solid var(--line,#dce6e2);border-radius:22px;padding:16px;margin:14px;box-shadow:0 8px 24px rgba(10,64,51,.05)}.wpt-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.wpt-head h2{margin:0;color:var(--brand,#0A4033)}.wpt-note{color:#60706a;line-height:1.7;font-size:13px}.wpt-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.wpt-box{border:1px solid #e2ece8;background:#fbfdfc;border-radius:16px;padding:12px}.wpt-box h3{margin:0 0 10px;color:#0A4033}.wpt-list{display:grid;gap:8px;max-height:310px;overflow:auto}.wpt-worker{display:flex;align-items:center;gap:8px;justify-content:space-between;border:1px solid #e5eeea;background:#fff;border-radius:13px;padding:9px}.wpt-worker label{margin:0!important;display:flex;align-items:center;gap:8px;color:#10231d!important;font-weight:800!important}.wpt-worker input{width:auto!important}.wpt-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.wpt-actions button{border:0;border-radius:12px;padding:10px 13px;font-weight:900;cursor:pointer}.wpt-light{background:#eef6f3!important;color:#0A4033!important;border:1px solid #dce6e2!important}.wpt-danger{background:#b83232!important;color:#fff!important}.wpt-open{border:1px solid #cfe8dc;background:#fff;border-radius:14px;padding:10px;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.wpt-open b{color:#0A4033}.wpt-pill{display:inline-block;border-radius:999px;background:#e8f4ee;color:#137a4b;padding:4px 9px;font-weight:900;font-size:12px;margin:2px}.wpt-toast{position:fixed;top:24px;left:50%;transform:translateX(-50%) translateY(-15px);z-index:999999;background:#0A4B3C;color:#fff;border-radius:18px;padding:14px 18px;box-shadow:0 18px 50px rgba(0,0,0,.2);font-family:Tahoma,Arial,sans-serif;opacity:0;transition:.22s ease;pointer-events:none;font-weight:900}.wpt-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}.wpt-toast.err{background:#b83232}.wpt-toast.warn{background:#8a6700}.wpt-table{overflow:auto;border:1px solid #dce6e2;border-radius:16px;background:#fff}.wpt-table table{width:100%;border-collapse:collapse}.wpt-table th,.wpt-table td{padding:9px;border-bottom:1px solid #edf1ef;text-align:right;white-space:nowrap}.wpt-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.wpt-kpi{border:1px solid #dce6e2;border-radius:16px;padding:12px;background:#fff}.wpt-kpi small{color:#60706a}.wpt-kpi b{display:block;font-size:25px;color:#0A4033;margin-top:6px}@media(max-width:900px){.wpt-grid,.wpt-kpis{grid-template-columns:1fr}.wpt-open{grid-template-columns:1fr}.wpt-card{margin:10px}}`;
    document.head.appendChild(st);
  }
  async function safeSelect(table,select='*',limit=5000){const c=sb(); if(!c)throw new Error('Supabase غير جاهز'); const r=await c.from(table).select(select).limit(limit); if(r.error)throw r.error; return r.data||[]}
  async function getWorkers(){
    let rows=[]; try{rows=await safeSelect('workers','*',5000)}catch(e){console.warn(e)}
    const uk=userKey(), un=userName();
    return rows.filter(w=>{const st=S(w.status||w.worker_status||w.active); if(/inactive|موقوف|false/.test(st))return false; const sup=[w.supervisor_id,w.supervisor_key,w.supervisor_name,w.supervisor,w.manager_name,w.project_supervisor].map(S).filter(Boolean); return !sup.length||sup.includes(uk)||sup.includes(un);}).map(w=>({key:S(w.id||w.worker_id||w.name||w.full_name),name:S(w.full_name||w.name||w.worker_name||w.employee_name||w.username||w.id),raw:w})).filter(w=>w.name);
  }
  async function getProjects(){let rows=[];try{rows=await safeSelect('projects','*',5000)}catch(e){console.warn(e)} return rows.map(p=>({key:S(p.id||p.project_id||p.name||p.project_name),name:S(p.project_name||p.name||p.title||p.id)})).filter(p=>p.name)}
  async function getGroups(){
    let rows=[]; try{rows=await safeSelect(GRP,'*',100)}catch(e){ }
    if(!rows.length) rows=[{group_key:'shaalan_50_51',group_name:'الشعلان 50/51',allocation:[{project_key:'الشعلان 50',project_name:'الشعلان 50',percent:50},{project_key:'الشعلان 51',project_name:'الشعلان 51',percent:50}]}];
    return rows.filter(g=>g.is_active!==false).map(g=>({key:S(g.group_key||g.id),name:S(g.group_name||g.name),allocation:typeof g.allocation==='string'?readJson(g.allocation,[]):A(g.allocation)}));
  }
  async function present(date){try{const {data,error}=await sb().from(ATT).select('*').eq('attendance_date',date).eq('supervisor_key',userKey()).eq('status','present').limit(1000); if(error)throw error; return data||[]}catch(e){toast('شغل ملف SQL الخاص بنظام العمال أولاً: '+(e.message||e),'err');return []}}
  async function openMovements(){const {data,error}=await sb().from(MOV).select('*').eq('supervisor_key',userKey()).eq('status','open').limit(1000); if(error)throw error; return data||[]}
  async function closeMovement(m,reason,t){t=t||nowIso(); const mins=minutesBetween(m.start_at,t); const {error}=await sb().from(MOV).update({end_at:t,actual_minutes:mins,status:'closed',close_reason:reason||'خروج',updated_at:t}).eq('id',m.id); if(error)throw error; return mins}
  function targetFromSelect(){const val=S($('wptTarget')?.value); const name=S($('wptTarget')?.selectedOptions?.[0]?.textContent); const type=val.startsWith('group:')?'group':'project'; const key=val.replace(/^group:|^project:/,''); const g=A(window.__wptGroups).find(x=>x.key===key); return {type,key,name:name.replace(/^مجموعة مشتركة - /,''),group:g,allocation:type==='group'?(g?.allocation||[]):[]}; }
  async function insertMovement(worker,target,notes){const now=nowIso(), date=S($('wptDate')?.value)||today(); const payload={idempotency_key:[date,userKey(),worker.key,target.type,target.key,now.slice(0,16)].join('|'),movement_date:date,supervisor_key:userKey(),supervisor_name:userName(),worker_key:worker.key,worker_name:worker.name,target_type:target.type,project_key:target.type==='project'?target.key:null,project_name:target.type==='project'?target.name:target.name,group_key:target.type==='group'?target.key:null,group_name:target.type==='group'?target.name:null,allocation:target.allocation||[],visit_type:S($('wptVisit')?.value)||'surface',start_at:now,status:'open',notes:S(notes)}; const r=await sb().from(MOV).insert(payload).select('*').single(); if(r.error){if(/duplicate/i.test(r.error.message||''))return null;throw r.error} return r.data}
  function selectedWorkers(prefix){return [...document.querySelectorAll(prefix+' input[type=checkbox]:checked')].map(i=>({key:i.value,name:i.dataset.name||i.value}))}
  async function renderSupervisor(){
    if(!$('supAttendance')&&!/supervisor/i.test(location.pathname))return; style();
    if(!$('wptPage')){
      const tabs=document.querySelector('.sup-tabs'); if(tabs){const btn=document.createElement('button');btn.className='sup-tab';btn.textContent='عمال المشاريع';btn.onclick=function(){document.querySelectorAll('.sup-tab').forEach(b=>b.classList.remove('active'));this.classList.add('active');document.querySelectorAll('.sup-page').forEach(p=>p.classList.remove('active'));$('wptPage').classList.add('active');};tabs.appendChild(btn)}
      const main=document.querySelector('.mobile-shell')||document.querySelector('.content')||document.body; const sec=document.createElement('section'); sec.id='wptPage'; sec.className='sup-page'; sec.innerHTML=`<div class="wpt-card"><div class="wpt-head"><div><h2>رحلة العمال اليومية</h2><div class="wpt-note">حضّر العمال من السكن، وزعهم على مشروع أو مجموعة مشتركة، وانقل العامل بدون تكرار وقت.</div></div><button class="wpt-light" onclick="TasneefWPT.loadSupervisor()">تحديث</button></div><div class="wpt-grid"><div class="wpt-box"><h3>1) تحضير العمال</h3><label>التاريخ</label><input type="date" id="wptDate"><div id="wptWorkers" class="wpt-list"></div><div class="wpt-actions"><button onclick="TasneefWPT.saveAttendance()">اعتماد الحضور</button></div></div><div class="wpt-box"><h3>2) دخول مشروع</h3><label>المشروع / المجموعة</label><select id="wptTarget"></select><label>نوع الزيارة</label><select id="wptVisit"><option value="surface">نظافة سطحية</option><option value="deep">نظافة عميقة</option><option value="support">مساندة</option></select><div id="wptPresent" class="wpt-list"></div><div class="wpt-actions"><button onclick="TasneefWPT.startSelected()">دخول العمال المختارين</button></div></div><div class="wpt-box"><h3>3) العمال المفتوحين</h3><div id="wptOpen" class="wpt-list"></div><label>نقل المحددين إلى</label><select id="wptTransferTarget"></select><div class="wpt-actions"><button class="wpt-light" onclick="TasneefWPT.transferSelected()">نقل عامل</button><button onclick="TasneefWPT.closeSelected()">خروج المحددين</button><button class="wpt-danger" onclick="TasneefWPT.closeAll()">إغلاق نهاية اليوم</button></div></div></div></div>`; main.appendChild(sec);
    }
    if($('wptDate')&&!$('wptDate').value)$('wptDate').value=today(); await loadSupervisor();
  }
  async function loadSupervisor(){
    window.__wptWorkers=await getWorkers(); window.__wptProjects=await getProjects(); window.__wptGroups=await getGroups(); const date=S($('wptDate')?.value)||today(); const pres=await present(date); const presentSet=new Set(pres.map(x=>S(x.worker_key))); const workers=A(window.__wptWorkers);
    $('wptWorkers').innerHTML=workers.length?workers.map(w=>`<div class="wpt-worker"><label><input type="checkbox" value="${esc(w.key)}" data-name="${esc(w.name)}" ${presentSet.has(w.key)?'checked':''}>${esc(w.name)}</label><span class="wpt-pill">${presentSet.has(w.key)?'حاضر':'جاهز'}</span></div>`).join(''):'<div class="wpt-note">لا يوجد عمال مرتبطون بهذا المشرف.</div>';
    const targets=[...A(window.__wptProjects).map(p=>`<option value="project:${esc(p.key)}">${esc(p.name)}</option>`),...A(window.__wptGroups).map(g=>`<option value="group:${esc(g.key)}">مجموعة مشتركة - ${esc(g.name)}</option>`)]; ['wptTarget','wptTransferTarget'].forEach(id=>{if($(id))$(id).innerHTML=targets.join('')});
    const presWorkers=pres.length?pres.map(p=>({key:S(p.worker_key),name:S(p.worker_name)})):workers.filter(w=>presentSet.has(w.key));
    $('wptPresent').innerHTML=presWorkers.length?presWorkers.map(w=>`<div class="wpt-worker"><label><input type="checkbox" value="${esc(w.key)}" data-name="${esc(w.name)}">${esc(w.name)}</label><span class="wpt-pill">متاح</span></div>`).join(''):'<div class="wpt-note">اعتمد حضور العمال أولاً.</div>';
    await renderOpen();
  }
  async function saveAttendance(){const date=S($('wptDate')?.value)||today(); const ws=selectedWorkers('#wptWorkers'); if(!ws.length){toast('حدد العمال الحاضرين أولاً','warn');return} const rows=ws.map(w=>({attendance_date:date,supervisor_key:userKey(),supervisor_name:userName(),worker_key:w.key,worker_name:w.name,status:'present',prepared_at:nowIso(),updated_at:nowIso()})); const r=await sb().from(ATT).upsert(rows,{onConflict:'attendance_date,supervisor_key,worker_key'}); if(r.error){toast('تعذر حفظ التحضير: '+r.error.message,'err');return} toast('تم تحضير '+ws.length+' عمال'); await loadSupervisor();}
  async function startSelected(){const ws=selectedWorkers('#wptPresent'); if(!ws.length){toast('حدد العمال للدخول','warn');return} const target=targetFromSelect(); const open=await openMovements(); for(const w of ws){for(const m of open.filter(x=>S(x.worker_key)===w.key)){await closeMovement(m,'نقل تلقائي',nowIso())} await insertMovement(w,target,'دخول من رحلة العمال')} toast('تم إدخال العمال على '+target.name); await renderOpen();}
  async function renderOpen(){const box=$('wptOpen'); if(!box)return; let rows=[]; try{rows=await openMovements()}catch(e){box.innerHTML='<div class="wpt-note">شغل ملف SQL أولاً.</div>';return} box.innerHTML=rows.length?rows.map(m=>`<div class="wpt-open"><div><label style="margin:0!important;color:#10231d!important"><input type="checkbox" value="${esc(m.id)}"> <b>${esc(m.worker_name)}</b></label><div class="wpt-note">${esc(m.project_name||m.group_name)} — بدأ: ${new Date(m.start_at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</div></div><button class="wpt-light" onclick="TasneefWPT.closeOne('${esc(m.id)}')">خروج</button></div>`).join(''):'<div class="wpt-note">لا يوجد عمال مفتوحين الآن.</div>';}
  async function closeIds(ids,reason){const rows=await openMovements(); for(const m of rows.filter(x=>ids.includes(S(x.id)))) await closeMovement(m,reason,nowIso()); toast('تم تسجيل الخروج'); await renderOpen();}
  async function closeOne(id){await closeIds([S(id)],'خروج')}
  async function closeSelected(){const ids=[...document.querySelectorAll('#wptOpen input:checked')].map(i=>i.value); if(!ids.length){toast('حدد العمال أولاً','warn');return} await closeIds(ids,'خروج')}
  async function closeAll(){const rows=await openMovements(); if(!rows.length){toast('لا يوجد عمال مفتوحين','warn');return} await closeIds(rows.map(r=>S(r.id)),'إغلاق نهاية اليوم')}
  async function transferSelected(){const ids=[...document.querySelectorAll('#wptOpen input:checked')].map(i=>i.value); if(!ids.length){toast('حدد العمال للنقل','warn');return} const target=targetFromSelect.call({}); const sel=$('wptTransferTarget'); const old=$('wptTarget').value; $('wptTarget').value=sel.value; const t=targetFromSelect(); $('wptTarget').value=old; const rows=await openMovements(); for(const m of rows.filter(x=>ids.includes(S(x.id)))){await closeMovement(m,'نقل',nowIso()); await insertMovement({key:S(m.worker_key),name:S(m.worker_name)},t,'نقل من مشروع آخر')} toast('تم نقل العمال إلى '+t.name); await renderOpen();}
  async function renderAdminMonthly(){
    if(!$('monthly'))return; style(); if($('wptMonthlyBox'))return; const sec=document.createElement('div'); sec.id='wptMonthlyBox'; sec.className='card'; sec.innerHTML=`<div class="wpt-head"><div><h2>أوقات العمال التفصيلية حسب المشاريع</h2><div class="wpt-note">تقرأ من رحلة العمال. المجموعة المشتركة مثل الشعلان 50/51 تُوزع تلقائيًا بدون تضخيم الساعات.</div></div><div><input type="month" id="wptMonth" value="${ymNow()}"><button onclick="TasneefWPT.loadMonthly()">تحميل</button></div></div><div id="wptKpis" class="wpt-kpis" style="margin:12px 0"></div><div class="wpt-table"><table><thead><tr><th>العامل</th><th>المشرف</th><th>المشروع</th><th>الدقائق</th><th>الساعات</th><th>المصدر</th></tr></thead><tbody id="wptMonthlyBody"></tbody></table></div>`; $('monthly').appendChild(sec); await loadMonthly();
  }
  async function loadMonthly(){const ym=S($('wptMonth')?.value)||ymNow(); const from=ym+'-01', to=new Date(Number(ym.slice(0,4)),Number(ym.slice(5,7)),1).toISOString().slice(0,10); let rows=[]; try{const r=await sb().from(MOV).select('*').gte('movement_date',from).lt('movement_date',to).eq('status','closed').limit(5000); if(r.error)throw r.error; rows=r.data||[]}catch(e){$('wptMonthlyBody').innerHTML=`<tr><td colspan="6">شغل ملف SQL أولاً: ${esc(e.message||e)}</td></tr>`;return} const map=new Map(); rows.forEach(r=>{const mins=N(r.actual_minutes); const alloc=A(typeof r.allocation==='string'?readJson(r.allocation,[]):r.allocation); if(r.target_type==='group'&&alloc.length){alloc.forEach(a=>add(r,S(a.project_name||a.project_key),mins*(N(a.percent)||0)/100,'مجموعة مشتركة'))}else add(r,S(r.project_name),mins,'مشروع مستقل')}); function add(r,project,mins,src){const key=[r.worker_key,r.supervisor_key,project].join('|'); const o=map.get(key)||{worker:r.worker_name,supervisor:r.supervisor_name,project,mins:0,src:new Set()}; o.mins+=mins; o.src.add(src); map.set(key,o)} const out=[...map.values()].sort((a,b)=>S(a.supervisor).localeCompare(S(b.supervisor))||S(a.worker).localeCompare(S(b.worker))); const total=out.reduce((s,r)=>s+r.mins,0); $('wptKpis').innerHTML=`<div class="wpt-kpi"><small>إجمالي الساعات</small><b>${(total/60).toFixed(1)}</b></div><div class="wpt-kpi"><small>عدد العمال</small><b>${new Set(out.map(r=>r.worker)).size}</b></div><div class="wpt-kpi"><small>عدد المشاريع</small><b>${new Set(out.map(r=>r.project)).size}</b></div><div class="wpt-kpi"><small>عدد السجلات</small><b>${rows.length}</b></div>`; $('wptMonthlyBody').innerHTML=out.length?out.map(r=>`<tr><td>${esc(r.worker)}</td><td>${esc(r.supervisor)}</td><td>${esc(r.project)}</td><td>${Math.round(r.mins)}</td><td>${(r.mins/60).toFixed(2)}</td><td>${esc([...r.src].join('، '))}</td></tr>`).join(''):'<tr><td colspan="6">لا توجد حركات عمال مغلقة لهذا الشهر.</td></tr>';}
  window.TasneefWPT={loadSupervisor,saveAttendance,startSelected,renderOpen,closeOne,closeSelected,closeAll,transferSelected,loadMonthly};
  function init(){renderSupervisor();renderAdminMonthly();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1200));else setTimeout(init,1200); setTimeout(init,3500);
})();
